name: security checks
on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 1 * * *' # dayly at 1:00 am

jobs:
  secrets-scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: scan for secrets
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
  dependency-scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: install dependencies
        run: pip install uv && uv sync --group dev
      - name: scan for vulnerable dependencies, run pip-audit
        run: uv run pip-audit 

  sast:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: install dependencies
        run: pip install uv && uv sync --group dev
      - name: run bandit for static application security testing
        run: uv run bandit -r src/

